pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'maven_3.6') {
                    sh 'mvn clean compile'
		    echo 'Started Compile Stage...';
		    echo "PATH = ${PATH}"
 		    echo "M2_HOME = ${M2_HOME}"
                    
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(maven : 'maven_3_5_0') {
		    echo 'Started Test Stage...'
                    sh 'mvn test'
                }
            }
        }
	
	stage ('Build Artifact Stage') {

            steps {
                withMaven(maven : 'maven_3_5_0') {
		    echo 'Started Build Artifact Stage...'
                    sh 'mvn install'
                }
            }
        }

        stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn deploy'
                }
            }
        }
    }
}
